### ISSUE TITLE
No content scraped

### ISSUE THREAD

**Issue by register4gk** [bocchilorenzo/scrapelex#2]
I run this on Windows 10 and Python 3.11 from Windows PowerShell

PS C:\Users\XXX\Downloads\scrapelex-main> python main.py
09-Sep-23 22:15:54 - Scraping category 80...
09-Sep-23 22:15:58 - Reached end of search results at page 1
09-Sep-23 22:15:58 - Scraping for 80 completed.
- Documents scraped: 0
- Documents without eurovoc classifiers: 0
- Average number of Eurovoc classifiers per document: 0

**Comment by register4gk** [comment]
Tried another one:
python main.py --language=de --year=2021 --clean

That gives:
09-Sep-23 22:47:05 - Currently at 10/1526 pages for 2021...
09-Sep-23 22:54:27 - Currently at 20/1526 pages for 2021...
09-Sep-23 23:01:31 - Currently at 30/1526 pages for 2021...
09-Sep-23 23:08:53 - Currently at 40/1526 pages for 2021...
09-Sep-23 23:16:19 - Currently at 50/1526 pages for 2021...
09-Sep-23 23:23:33 - Currently at 60/1526 pages for 2021...

However:
The script creates the directory on harddisk, however no files are written to \eurlexdata\de\docsHTML\2021

**Comment by bocchilorenzo** [comment]
Hi,
regarding the first issue, the problem is that category 80 does not exist. If you're unsure about which category you can use, I advise you to run the script as `python main.py --get_categories`. This will return every category and its full name.

Regarding the second issue, the default option is to not save the files, since the usage of the script was meant to be used both via command line and regular scripts where one might want to handle the saving in a different way. Anyways, to save the html of each downloaded page (both search page and single article), you can add the --save_html option. If you also add --save_data, the script will extract the data from each article and save everything once the year/category has been fully scraped. 

My suggestion would be to save only the html first, and then, once the script has finished, to launch the scraping of the articles with multiprocessing to greatly speed up the process. To do so, simply launch the script first with `python main.py --language=de --year 2021 --clean --save_html` and then launch `python main.py --language=de --year 2021 --scrape_local --multi_core --cpu_count <insert_number>`, where <insert_number> is the maximum number of processes you want to use.

**Comment by register4gk** [comment]
Thank you!

(1) Works: 
`python main.py --get_categories`

(2) Works:
`python main.py --language=de --year 2023 --clean --save_html`
Result print:

16-Sep-23 03:18:09 - Scraping for 2023 completed.
- Documents scraped: 8350
- Documents without eurovoc classifiers: 8350
- Average number of Eurovoc classifiers per document: 0.0

I don't know whether the output for Eurovoc classifiers is expected.

(3) Does not work
`python main.py --language=de --year 2021 --scrape_local --multi_core --cpu_count 2`
Result print:

Directory ./eurlexdata/de\docsHTML\2 not found. Skipping...
Scraping documents in ./eurlexdata/de\docsHTML\2...
Traceback (most recent call last):
  File "C:\Users\SANATIZED\scrapelex-main\main.py", line 60, in <module>
    documents = scraper.get_documents_local_multiprocess(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SANATIZED\scrapelex-main\scraper\scrapelex.py", line 982, in get_documents_local_multiprocess
    (file, dir_scrape, label_types) for file in listdir(dir_scrape) if file.endswith(".gz")
                                                ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: './eurlexdata/de\\docsHTML\\2'
PS C:\Users\SANATIZED\scrapelex-main> python main.py --language=de --year 2021 --scrape_local --multi_core --cpu_count 2
Directory ./eurlexdata/de\docsHTML\2 not found. Skipping...
Scraping documents in ./eurlexdata/de\docsHTML\2...
Traceback (most recent call last):
  File "C:\Users\SANATIZED\scrapelex-main\main.py", line 60, in <module>
    documents = scraper.get_documents_local_multiprocess(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SANATIZED\scrapelex-main\scraper\scrapelex.py", line 982, in get_documents_local_multiprocess
    (file, dir_scrape, label_types) for file in listdir(dir_scrape) if file.endswith(".gz")
                                                ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: './eurlexdata/de\\docsHTML\\2'

**I assume that I have another problem with executing the script on a Windows machine related to path names**

**Comment by bocchilorenzo** [comment]
The error should be fixed in the latest commit, please try cloning the repo again

**Comment by register4gk** [comment]
Thank you! It works.
