### ISSUE TITLE
Feature request - Format of json File

### ISSUE THREAD

**Issue by register4gk** [bocchilorenzo/scrapelex#3]
Hi Lorenzo

I would like to import the json file
C:\Users\SANATIZED\scrapelex-main\eurlexdata\de\extracted\2023.json.gz
into a Directus instance similar to
https://learndirectus.com/how-to-import-data-into-directus-using-json/

However this does not work - probably due to missing linebreaks and other formatting issues. Would it be possible to change the json file formatting?

**Comment by bocchilorenzo** [comment]
Hi,
the json file should be able to be imported without issue, but first it has to be extracted because the .json.gz is a compressed version of the file. On windows, 7zip and winrar should be able to do that. Each document in the json is saved in the format:
`"document_id": {"title": ...,
    "link": ...,
    "eurovoc_classifiers": ...,
    "full_text": ...}`

**Comment by register4gk** [comment]
Hi Lorenzo,
Thank you! I extracted to .json from the .json.gz however still have the problem. From some trial and error, I believe this is due the missing object name for the "document_id".

Would it be possible to change the format to the following?

"document_id": "xxx" {"title": ..., "link": ..., "eurovoc_classifiers": ..., "full_text": ...}
or
{"document_id": ...,"title": ..., "link": ..., "eurovoc_classifiers": ..., "full_text": ...}

**Comment by bocchilorenzo** [comment]
Unfortunately I can't change the format because the scraper is being used in another project and we need to keep the format. Anyways, you can use the script you find [here](https://gist.github.com/bocchilorenzo/94a1785d306abcdea6e1aa6abe8479f1) to convert your files. Simply download it and launch it with the arguments `--input_dir` for the directory that contains the .json.gz files to convert and `--output_dir` that will contain the converted .json files. Each .json will contain a list where each element is a dictionary for the document which also contains the document id (essentially, the second format you proposed). Let me know if it works

**Comment by register4gk** [comment]
Thank you! This script works nicely. I can convert the file and upload it to Directus.
